### ISSUE TITLE
Branch not found on CI

### ISSUE THREAD

**Issue by nodejsjs** [ismaeldivita/change-tracker-plugin#10]
I have a master branch and I'm trying to test this plugin on the CI. I branched off of master into a new branch called `a` and installed the plugin in branch `a`.

in branch `a`:
```
changeTracker {
    tasks = ['testDebugUnitTest']
    branch = "a"
}
```

Then I branched off of branch `a` into branch `b` to test the changedModules task. In this branch I just made a small change in one of the modules. I pushed both branches and triggered a CI build on branch `b` and ran the command `gradlew changedModules` on CI. The branches look like the following:
```
------  master
             \
               a ----- commit (install the plugin)
                            \
                             b ------ commit (minor change in a module)
```
The CI build failed with the following error:
```
Caused by: org.gradle.api.GradleException: Branch  a not found
```

I've tried adding `remote` in the config block and tried other variations of the branch name like `origin/a` or `remotes/origin/a`, etc, but nothing works. Locally, if I'm on branch `b` and run `./gradlew changedModules`, then it runs fine and prints out a nice report. Not sure what's going on in the CI. Somehow the branch name is the issue. Any ideas?

**Comment by ismaeldivita** [comment]
Hi 👋 

You're right about adding the remote, this will be necessary for most CI runs since they don't checkout local branches. Just the remote name is expected by the plugin e.g., "origin".

Can you give more details how your CI works? Are you using an internal solution or a third party like Bitrise or CircleCi?

About your problem, normally one of the first CI tasks is the git setup. For PR's, most of them fetch both branches, the base and the one you want to merge, in your example `master` and `b`, then they will merge the `b` into `master` and run the verification tasks. Can you double check if you're fetching the branches you need before run your task?

**Comment by nodejsjs** [comment]
Hi. The CI is bitrise. You're right. After investigating the `git` step on bitrise, I found that it doesn't clone the whole repo. It creates an empty git repo, adds the origin, and ONLY fetches the pr branch (not even master) and runs the rest of the CI steps on the branch. I guess cloning the whole repo will add more time to the build process. I just now need to figure out how tell the git step plugin on bitrise to also fetch the `master` (or `a` in this case) branch so that the plugin can compare the diff.

Thanks for your help!
